-- §63.1. No ticket is ever merged without somebody saying so.
--
-- Intake merged silently: two form rows with the same mobile and order id and
-- the second became a child of the first, unasked. It is usually right and
-- occasionally wrong, and when it is wrong the second complaint has vanished
-- into a thread nobody is reading. So the match becomes a *suggestion* the
-- person working the ticket confirms.
--
-- ---------------------------------------------------------------------------
-- A table, not a column.
-- ---------------------------------------------------------------------------
--
-- `possible_duplicate_of bigint` was the alternative and cannot carry what §63.1
-- needs. Three things decided it:
--
--   * "Keep separate" has to be remembered per pair, so the prompt never comes
--     back for those two tickets. A column has nowhere to put that, so a second
--     place would have been needed anyway — and then the pair lives in two
--     places.
--   * The prompt fires in either direction. With a column, "does anything point
--     at me" is a second index and a second query; with a normalised pair it is
--     one row found from either side.
--   * One order id can collect several tickets. A column holds the last match
--     and silently forgets the rest.
create table support.duplicate_candidates (
  id          bigint generated by default as identity primary key,
  -- Always the lower id first, so a pair is one row however it was found.
  lo_ticket_id bigint not null references support.tickets (id) on delete cascade,
  hi_ticket_id bigint not null references support.tickets (id) on delete cascade,
  /** The order id the two share — what the suggestion is based on. */
  order_id     text not null,
  detected_at  timestamptz not null default now(),
  /** Set by "Keep separate". A dismissed pair is never suggested again. */
  dismissed_at timestamptz,
  dismissed_by uuid references public.profiles (id),
  /** Set when the pair was actually merged, so the chip stops showing. */
  merged_at    timestamptz,
  constraint duplicate_pair_ordered check (lo_ticket_id < hi_ticket_id),
  constraint duplicate_pair_unique unique (lo_ticket_id, hi_ticket_id)
);

comment on table support.duplicate_candidates is
  '§63.1. Suggested duplicates, by order id. A row is live until it is dismissed '
  '("Keep separate") or merged. Pairs are stored lo < hi so either direction '
  'finds them in one lookup.';

-- The queue asks "has this ticket a live candidate" once per row.
create index duplicate_candidates_lo_idx on support.duplicate_candidates (lo_ticket_id)
  where dismissed_at is null and merged_at is null;
create index duplicate_candidates_hi_idx on support.duplicate_candidates (hi_ticket_id)
  where dismissed_at is null and merged_at is null;

alter table support.duplicate_candidates enable row level security;

create policy duplicate_candidates_support_all on support.duplicate_candidates
  for all to authenticated using (app.is_support()) with check (app.is_support());

grant select, insert, update on support.duplicate_candidates to authenticated, service_role;
grant usage, select on all sequences in schema support to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Detecting one.
-- ---------------------------------------------------------------------------
--
-- Order id alone. Mobile is deliberately out of the match: §63.1 dropped it
-- because a parent ringing about two children's orders shares a number and
-- nothing else, and that pairing was the one most likely to be wrong.
create or replace function support.record_duplicate_candidate(p_ticket_id bigint)
returns bigint
language plpgsql
security definer
set search_path to ''
as $fn$
declare
  t      support.tickets%rowtype;
  v_other bigint;
  v_id    bigint;
begin
  select * into t from support.tickets where id = p_ticket_id;
  if t.id is null or t.order_id is null or t.parent_ticket_id is not null then
    return null;
  end if;

  -- The oldest live ticket sharing the order id. Oldest, because the default
  -- merge direction is newer into older and the suggestion should name the one
  -- that would survive.
  select x.id into v_other
    from support.tickets x
   where x.id <> t.id
     and x.order_id = t.order_id
     and x.parent_ticket_id is null
     and x.status <> 'resolved'
   order by x.id
   limit 1;

  if v_other is null then return null; end if;

  insert into support.duplicate_candidates (lo_ticket_id, hi_ticket_id, order_id)
  values (least(t.id, v_other), greatest(t.id, v_other), t.order_id)
  -- Already suggested, dismissed or merged: leave whatever was decided alone.
  on conflict (lo_ticket_id, hi_ticket_id) do nothing
  returning id into v_id;

  return v_id;
end $fn$;

grant execute on function support.record_duplicate_candidate(bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- The live candidate for one ticket, in either direction.
-- ---------------------------------------------------------------------------
create or replace function support.duplicate_candidate_of(p_ticket_id bigint)
returns table (
  candidate_id bigint, other_ticket_id bigint, order_id text,
  other_issues text[], other_issue_other text, other_status support.ticket_status,
  /** Which way a merge would go by default: newer into older. */
  child_id bigint, parent_id bigint,
  same_issue boolean
)
language sql
stable
set search_path to ''
as $$
  with me as (select * from support.tickets where id = p_ticket_id),
  pair as (
    select d.id, d.order_id,
           case when d.lo_ticket_id = p_ticket_id then d.hi_ticket_id
                else d.lo_ticket_id end as other_id
      from support.duplicate_candidates d
     where (d.lo_ticket_id = p_ticket_id or d.hi_ticket_id = p_ticket_id)
       and d.dismissed_at is null
       and d.merged_at is null
     order by d.id
     limit 1
  )
  select p.id, o.id, p.order_id,
         o.issues_work, o.issue_other_work, o.status,
         greatest(m.id, o.id), least(m.id, o.id),
         -- Identical sets, or both empty. The wording of the prompt turns on
         -- this, so it is answered here rather than in two screens.
         (m.issues_work <@ o.issues_work and o.issues_work <@ m.issues_work)
    from pair p
    join me m on true
    join support.tickets o on o.id = p.other_id
   -- A candidate whose other half has since been merged away is not a candidate.
   where o.parent_ticket_id is null;
$$;

grant execute on function support.duplicate_candidate_of(bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- "Keep separate".
-- ---------------------------------------------------------------------------
create or replace function support.dismiss_duplicate_candidate(
  p_ticket_id bigint,
  p_other_id  bigint
)
returns bigint
language plpgsql
security invoker
set search_path to ''
as $fn$
declare v_id bigint;
begin
  if not app.is_support() then raise exception 'not permitted'; end if;

  update support.duplicate_candidates
     set dismissed_at = now(), dismissed_by = (select auth.uid())
   where lo_ticket_id = least(p_ticket_id, p_other_id)
     and hi_ticket_id = greatest(p_ticket_id, p_other_id)
     and dismissed_at is null
     and merged_at is null
  returning id into v_id;

  if v_id is null then
    -- Nothing live to dismiss. Not an error: two people can answer the same
    -- prompt, and the second should simply find it already settled.
    return null;
  end if;

  -- Both tickets get the decision on their timeline, because "we looked and they
  -- are different" is a judgement worth finding six weeks later.
  insert into support.events (ticket_id, actor_id, kind, detail) values
    (p_ticket_id, (select auth.uid()), 'note',
     jsonb_build_object('text', 'Kept separate from #' || p_other_id
                                || ' — same order id, judged a different issue.')),
    (p_other_id, (select auth.uid()), 'note',
     jsonb_build_object('text', 'Kept separate from #' || p_ticket_id
                                || ' — same order id, judged a different issue.'));
  return v_id;
end $fn$;

grant execute on function support.dismiss_duplicate_candidate(bigint, bigint)
  to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- A merge settles the pair.
-- ---------------------------------------------------------------------------
--
-- merge_ticket is restated rather than patched: its body carries its own `case`
-- and `end if` keywords and a regex over plpgsql has bitten this project before.
do $mig$
declare src text; patched text;
begin
  select pg_get_functiondef(p.oid) into src
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'support' and p.proname = 'merge_ticket';

  patched := replace(src,
$old$  update support.tickets set last_touched_at = v_now where id = p_parent_id;
  return p_parent_id;$old$,
$new$  update support.tickets set last_touched_at = v_now where id = p_parent_id;

  -- §63.1. The suggestion, if there was one, is now settled — whichever
  -- direction it was recorded in, and whether or not this merge came from the
  -- prompt or from "Merge into…" by hand.
  update support.duplicate_candidates
     set merged_at = v_now
   where lo_ticket_id = least(p_child_id, p_parent_id)
     and hi_ticket_id = greatest(p_child_id, p_parent_id)
     and merged_at is null;

  return p_parent_id;$new$);

  if patched = src then raise exception 'merge_ticket: the tail was not matched'; end if;
  execute patched;
end $mig$;

notify pgrst, 'reload schema';
