-- §58. Support Tickets — a module of its own, in a schema of its own.
--
-- This is NOT the counselling after-sale queue. That one lives in
-- public.enquiries (type = 'after_sale') and is driven by logged calls: a
-- status there is *derived* by app.recompute_enquiry() from the latest call's
-- outcome, which is why moving a ticket on that screen means inserting a call.
--
-- Support tickets are the opposite shape. They arrive from a Google Form the
-- students fill in, they carry their own status the team sets directly, and
-- their history is an explicit event log rather than a side effect of calls.
-- Putting them in public.enquiries would have meant one recompute function
-- serving two contradictory rules, so they get schema `support` and share
-- nothing with counselling but the master lists and the profiles table.
--
-- The counselling link is a column, not a merge: §58.4 of the next brief hangs
-- off an after-sale escalation, and when that lands it needs somewhere to point.

create schema if not exists support;

comment on schema support is
  'Support Tickets (§58). Separate from the counselling after-sale queue in '
  'public.enquiries — different intake, different status rule, different history.';

-- §58.2. Who may work support.
--
-- app.is_staff() is the wrong gate: it includes counsellors, and §58.0 is
-- explicit that counsellors do not see this module at all. app.is_admin() is
-- too narrow — the ticket team is the point.
create or replace function app.is_support()
returns boolean
language sql
stable
set search_path to ''
as $$
  select app.role() in (
    'ticket_team'::public.user_role,
    'manager'::public.user_role,
    'super_admin'::public.user_role
  );
$$;

grant execute on function app.is_support() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Vocabularies.
-- ---------------------------------------------------------------------------

-- 'form' is 94% of the feed (the sheet calls it "Student"). 'counselling' is
-- reserved for the escalation hook and is not yet written by anything.
create type support.ticket_source as enum
  ('form', 'mail', 'whatsapp', 'calling_team', 'counselling', 'manual');

-- The team's live vocabulary on the sheet is only Closed / Duplicate /
-- On-Hold-Escalated, and 'Duplicate' is not a status here — a duplicate is a
-- child with parent_ticket_id set, which is a fact about the row rather than a
-- state of the complaint.
create type support.ticket_status as enum
  ('new', 'working', 'escalated', 'future', 'resolved');

create type support.event_kind as enum
  ('created', 'field_change', 'status_change', 'note', 'called', 'messaged',
   'merged_into', 'child_merged', 'resolved', 'reopened', 'counselling_link');

-- §58.1. The five checkbox options, exactly as the form emits them.
--
-- Held as a constant array so the check constraint, the parser and the UI
-- cannot drift apart. 'akash' is deliberately NOT here: it occurs on 245 of
-- 5,530 historic rows and behaves like a sixth checkbox, but nobody has said
-- what it means, so it lands in issue_other where it is visible rather than
-- being silently promoted to a category.
create or replace function support.issue_options()
returns text[]
language sql
immutable
set search_path to ''
as $$
  select array[
    'Tracking ID Issues',
    'Courier & Delivery Issues',
    'Link / Serial Key Mail not received',
    'Technical Issue / Course Extension',
    'Received Damaged/Defective Product'
  ]::text[];
$$;

grant execute on function support.issue_options() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- support.tickets
-- ---------------------------------------------------------------------------

create table support.tickets (
  -- The number the team says out loud, so identity is a plain counter and not
  -- a uuid nobody can read over a phone.
  id                bigint generated by default as identity primary key,
  created_at        timestamptz not null default now(),
  source            support.ticket_source not null,
  -- The form's own timestamp for form tickets; now() for everything else. The
  -- feed's timestamps parse 5,530 of 5,530, so this is trustworthy — unlike
  -- the sheet's mirrored Date column, which reads "Invalid Date" throughout.
  raised_at         timestamptz not null default now(),

  -- ---- as submitted. Never edited; the working copies below are what the
  -- ---- team changes, so the original stays readable next to it forever.
  student_name      text,
  mobile_raw        text,
  mobile            text check (mobile ~ '^[6-9][0-9]{9}$'),
  order_id_raw      text,
  order_id          text,
  issues_raw        text,
  issues            text[] not null default '{}'
                      check (issues <@ support.issue_options()),
  issue_other       text,
  description       text,
  -- Kept whole and authoritative. One ticket can name two institutes (304 of
  -- 5,160 historic cells do) and the Other text arrives in the same cell
  -- carrying its own slashes and commas, so no pair of ids can represent this
  -- field without losing something. institute_id/teacher_id below are the
  -- team's working answer to "who is this about", not a parse of this string.
  faculty_raw       text,
  -- 15 months of history has exactly one Drive URL per ticket and never more,
  -- but the form emits a comma-separated list when several files are allowed,
  -- so the column is already the right shape for that day.
  attachment_urls   text[] not null default '{}',
  -- Sheet row identity, for idempotency. Null for tickets not from the form;
  -- Postgres lets a unique index hold many nulls, which is what we want.
  form_row_ref      text unique,

  -- ---- working fields
  order_id_work     text,
  institute_id      uuid references public.institutes (id),
  teacher_id        uuid references public.teachers (id),
  issues_work       text[] not null default '{}'
                      check (issues_work <@ support.issue_options()),
  issue_other_work  text,
  status            support.ticket_status not null default 'new',
  follow_up_date    date,
  escalated_to      uuid references public.profiles (id),
  resolved_at       timestamptz,
  resolved_by       uuid references public.profiles (id),

  -- ---- merge
  parent_ticket_id  bigint references support.tickets (id),
  merged_at         timestamptz,

  assigned_to       uuid references public.profiles (id),
  last_touched_at   timestamptz not null default now(),

  -- §58.4 hook. The counselling side escalates an after_sale enquiry by
  -- logging a call with outcome 'escalated'; when that raises a support
  -- ticket, this is where it points.
  counselling_enquiry_id bigint references public.enquiries (id),

  -- A state that says work is outstanding has to say when it is next looked
  -- at. The team has filled a follow-up date on 24 of 5,999 sheet rows, so
  -- this is a real change of habit and not a formality.
  constraint tickets_followup_required check (
    status not in ('working', 'escalated', 'future') or follow_up_date is not null
  ),
  constraint tickets_escalatee_required check (
    status <> 'escalated' or escalated_to is not null
  ),
  constraint tickets_resolved_stamped check (
    status <> 'resolved' or resolved_at is not null
  ),
  -- A ticket cannot be its own duplicate, and a merge is dated when it happens.
  constraint tickets_parent_not_self check (parent_ticket_id is distinct from id),
  constraint tickets_merge_dated check (
    (parent_ticket_id is null) = (merged_at is null)
  )
);

comment on column support.tickets.parent_ticket_id is
  'Set means this ticket is a duplicate merged into another. A child never '
  'appears in the queue on its own; its events append to the parent timeline.';

-- The auto-merge probe on create, and the manual "merge into…" search. Partial,
-- because it only ever asks about live parents.
create index tickets_merge_probe_idx
  on support.tickets (mobile, order_id)
  where parent_ticket_id is null and status <> 'resolved';

create index tickets_queue_idx on support.tickets (status, follow_up_date, raised_at)
  where parent_ticket_id is null;
create index tickets_parent_idx on support.tickets (parent_ticket_id)
  where parent_ticket_id is not null;
create index tickets_mobile_idx on support.tickets (mobile);
create index tickets_order_idx on support.tickets (order_id);
create index tickets_assigned_idx on support.tickets (assigned_to);
create index tickets_institute_idx on support.tickets (institute_id);
create index tickets_teacher_idx on support.tickets (teacher_id);
create index tickets_issues_idx on support.tickets using gin (issues_work);
create index tickets_counselling_idx on support.tickets (counselling_enquiry_id)
  where counselling_enquiry_id is not null;

-- ---------------------------------------------------------------------------
-- support.events
-- ---------------------------------------------------------------------------
--
-- Named `events`, not `ticket_events`, on purpose: audit.log_change() records
-- tg_table_name *unqualified*, so a support.ticket_events would be
-- indistinguishable from public.ticket_events in audit_log — same name, same
-- bigint row_pk. Renaming costs nothing; patching the shared audit function
-- would split the existing accounts.* history in two.
create table support.events (
  id        bigint generated by default as identity primary key,
  ticket_id bigint not null references support.tickets (id) on delete cascade,
  at        timestamptz not null default now(),
  -- Null for system work: the intake endpoint runs as the service role and has
  -- no person behind it.
  actor_id  uuid references public.profiles (id),
  kind      support.event_kind not null,
  detail    jsonb not null default '{}'::jsonb
);

create index events_ticket_idx on support.events (ticket_id, at desc, id desc);
create index events_kind_idx on support.events (kind);

comment on column support.events.detail is
  'Shape depends on kind: field_change {field, old, new}; status_change '
  '{old, new, follow_up_date, escalated_to}; note {text}; called {picked, '
  'note}; messaged {channel, note}; merged_into/child_merged {ticket_id}.';

-- ---------------------------------------------------------------------------
-- §58.1. Faculty aliases.
-- ---------------------------------------------------------------------------
--
-- The form's Faculty/Institute field is a dropdown whose options are slash-
-- joined faculty rosters standing in for a seller, plus an Other box. Matching
-- the raw text against master names — the obvious rule — resolves 22% of
-- 5,160 historic cells, because the biggest option by far is a roster string
-- that equals no institute's name.
--
-- Nor can the rosters be derived: our masters file each teacher under their own
-- institute while the form groups them by who sells the course, so only 2 of
-- the 5 real rosters have segments that agree. A majority vote would be a guess
-- printed as a fact, so the mapping is stated here, once, where it can be read
-- and corrected.
create table support.faculty_aliases (
  -- Lower-cased, trimmed, honorifics and trailing separators removed. See
  -- lib/support/normalise.ts, which must produce exactly this.
  raw_norm     text primary key,
  institute_id uuid references public.institutes (id),
  teacher_id   uuid references public.teachers (id),
  note         text,
  created_at   timestamptz not null default now(),
  constraint faculty_alias_points_somewhere check (
    institute_id is not null or teacher_id is not null
  )
);

comment on table support.faculty_aliases is
  'Raw Faculty/Institute strings the form emits, mapped to Calman masters. '
  'Consulted before exact-name matching. A row here is a decision, not a '
  'derivation — the note says what the evidence was.';

-- The five real roster options, by frequency in the July-2025-onwards feed.
-- Segment votes are recorded because three of the five are not unanimous: the
-- reading is "the seller is the house named in the listing", which the team can
-- overrule per ticket, since faculty_raw is kept on every row.
insert into support.faculty_aliases (raw_norm, institute_id, teacher_id, note) values
  ('bhanwar borana/shubham keswani/aakash kandoi/sankalp kanstiya',
   (select id from public.institutes where name = 'BB Virtuals'), null,
   '2,286 rows. Segments: BB Virtuals 3, Vsmart Academy 1 (Sankalp Kanstiya is '
   'filed under Vsmart in our masters). Read as BB Virtuals'' combo listing.'),
  ('vishal bhattad/jai chawla/ravi taori/shubham singhal/prashant sarda',
   (select id from public.institutes where name = 'Vsmart Academy'), null,
   '581 rows. All 5 segments are Vsmart Academy.'),
  ('sarthak jain/riddhi baghmar/adish jain/amit sharma',
   (select id from public.institutes where name = 'Fast Education'), null,
   '104 rows. Segments: Fast Education 3, Amit Sharma 1 (own institute).'),
  ('vijay sarda/darshan khare/rishabh jain/abhishek zaware',
   (select id from public.institutes where name = 'Ekatvam Academy'), null,
   '104 rows. All 4 segments are Ekatvam Academy.'),
  ('swapnil patni/ankita patni/harshad jaju/anand bhangariya/pooja kamdar date',
   (select id from public.institutes where name = 'Swapnil Patni Classes'), null,
   '77 rows. Segments: Swapnil Patni Classes 2, HJ Classes 1, Anand Bhangariya '
   '1, Pooja Kamdar Date 1. Read as the Swapnil Patni listing.'),
  -- Spellings and abbreviations the team and the students actually type. The
  -- exact-name rule already covers correctly spelled names, so only the misses
  -- are listed.
  ('shubham keshwani', null,
   (select id from public.teachers where name = 'Shubham Keswani'),
   '12 rows, misspelling.'),
  ('tarun raj', null,
   (select id from public.teachers where name = 'Tharun Raj'),
   '7 rows, misspelling.'),
  ('vsmart', (select id from public.institutes where name = 'Vsmart Academy'), null,
   'The team''s own abbreviation on the sheet (342 rows).'),
  ('fast edu', (select id from public.institutes where name = 'Fast Education'), null,
   'The team''s own abbreviation on the sheet (189 rows).'),
  ('ekatvam', (select id from public.institutes where name = 'Ekatvam Academy'), null,
   'The team''s own abbreviation on the sheet (152 rows).');

-- 'Bhanwar Borana and Vishal Bhattad (Only for Combos)' (60 rows) is
-- deliberately absent: it names two houses and there is no honest single
-- answer. The team fills it per ticket.
--
-- 'Zeroinfy books' (34 rows) is absent because no such institute exists — it is
-- Zeroinfy's own stock, not a faculty, and inventing a master row for it is not
-- this migration's business.
--
-- 'Nitin Nahar' (11 rows) is absent because the teacher is missing from
-- public.teachers altogether. Flagged rather than fixed: masters are not
-- this brief's to change.

-- ---------------------------------------------------------------------------
-- Audit.
-- ---------------------------------------------------------------------------
--
-- last_touched_at is excluded: it moves on every write by definition, and
-- without excluding it the "nothing a human changed" test in audit.log_change
-- would never fire and every touch would log a row.
create trigger z_audit_support_tickets
  after insert or delete or update on support.tickets
  for each row execute function audit.log_change('last_touched_at');

create trigger z_audit_support_events
  after insert or delete or update on support.events
  for each row execute function audit.log_change();

-- ---------------------------------------------------------------------------
-- RLS. ticket_team, manager, super_admin read and write; counsellor nothing;
-- anon nothing. The intake endpoint uses the service role, which bypasses RLS
-- and is gated by a shared secret in the route instead.
-- ---------------------------------------------------------------------------

alter table support.tickets         enable row level security;
alter table support.events          enable row level security;
alter table support.faculty_aliases enable row level security;

create policy tickets_support_all on support.tickets
  for all to authenticated using (app.is_support()) with check (app.is_support());

create policy events_support_all on support.events
  for all to authenticated using (app.is_support()) with check (app.is_support());

create policy aliases_support_read on support.faculty_aliases
  for select to authenticated using (app.is_support());

create policy aliases_admin_write on support.faculty_aliases
  for all to authenticated using (app.is_admin()) with check (app.is_admin());

-- PostgREST reaches a schema only if it is exposed and usable. The grants are
-- deliberately narrow: no anon, anywhere.
grant usage on schema support to authenticated, service_role;
grant select, insert, update on support.tickets to authenticated, service_role;
grant select, insert on support.events to authenticated, service_role;
grant select on support.faculty_aliases to authenticated, service_role;
grant insert, update, delete on support.faculty_aliases to authenticated, service_role;
grant usage, select on all sequences in schema support to authenticated, service_role;

revoke all on schema support from anon;

notify pgrst, 'reload schema';
